In [1]:
import numpy as np

# 1. Create arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Array1:", array1)
print("Array2:\n", array2)

# 2. Array properties
print("Array1 shape:", array1.shape)
print("Array2 shape:", array2.shape)
print("Array1 size:", array1.size)
print("Array2 size:", array2.size)

# 3. Reshape array
array3 = np.arange(12).reshape((3, 4))
print("Array3 reshaped:\n", array3)

# 4. Array slicing
slice1 = array3[1, :]
print("Slice1:", slice1)
slice2 = array3[:, 2]
print("Slice2:", slice2)

# 5. Array operations
array4 = np.array([10, 20, 30, 40, 50])
print("Array1 + Array4:", array1 + array4)
print("Array1 * Array4:", array1 * array4)
print("Array1 ** 2:", array1 ** 2)

# 6. Universal functions
print("Sine of Array1:", np.sin(array1))
print("Log of Array4:", np.log(array4))

# 7. Array aggregation
print("Sum of Array1:", np.sum(array1))
print("Mean of Array4:", np.mean(array4))

# 8. Broadcasting
array5 = np.array([1, 2, 3])
array6 = np.array([[1], [2], [3]])
print("Broadcasting:\n", array5 + array6)

# 9. Stacking arrays
stacked_array = np.hstack((array1.reshape(5, 1), array4.reshape(5, 1)))
print("Horizontally stacked array:\n", stacked_array)

# 10. Splitting arrays
split_array = np.hsplit(stacked_array, 2)
print("Split array 1:\n", split_array[0])
print("Split array 2:\n", split_array[1])

# 11. Array copying
array7 = np.copy(array1)
print("Copied Array7:", array7)

# 12. Linear algebra
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print("Matrix multiplication:\n", np.dot(matrix1, matrix2))
print("Matrix determinant:", np.linalg.det(matrix1))

# 13. Random numbers
random_array = np.random.rand(3, 3)
print("Random array:\n", random_array)

# 14. Sorting arrays
sorted_array = np.sort(array4)
print("Sorted Array4:", sorted_array)

# 15. Array indices
indices = np.where(array4 > 20)
print("Indices where Array4 > 20:", indices)

# 16. Array masking
mask = array4 > 20
print("Array4 with mask applied:", array4[mask])

# 17. Fancy indexing
fancy_indexed_array = array4[[0, 2, 4]]
print("Fancy indexed array:", fancy_indexed_array)

# 18. Array concatenation
concatenated_array = np.concatenate((array1, array4))
print("Concatenated array:", concatenated_array)

# 19. Array splitting
split_array2 = np.array_split(concatenated_array, 3)
print("Split array parts:")
for part in split_array2:
    print(part)

# 20. Array flattening
flattened_array = array2.flatten()
print("Flattened Array2:", flattened_array)

# 21. Array transpose
transposed_array = array2.T
print("Transposed Array2:\n", transposed_array)

# 22. Array inversion
inverted_matrix = np.linalg.inv(matrix1)
print("Inverted Matrix1:\n", inverted_matrix)

# 23. Diagonal elements
diagonal_elements = np.diag(matrix1)
print("Diagonal elements of Matrix1:", diagonal_elements)

# 24. Array multiplication element-wise
elementwise_mult = np.multiply(array1, array4)
print("Element-wise multiplication:", elementwise_mult)

# 25. Generating a sequence of numbers
sequence = np.arange(10, 21, 2)
print("Generated sequence:", sequence)

# 26. Generating random integers
random_integers = np.random.randint(1, 100, size=(5,))
print("Random integers:", random_integers)

# 27. Cumulative sum
cumulative_sum = np.cumsum(array1)
print("Cumulative sum of Array1:", cumulative_sum)

# 28. Tile an array
tiled_array = np.tile(array1, 2)
print("Tiled Array1:", tiled_array)

# 29. Repeat elements
repeated_elements = np.repeat(array1, 2)
print("Repeated elements of Array1:", repeated_elements)

# 30. Unique elements
unique_elements = np.unique(array4)
print("Unique elements in Array4:", unique_elements)

# 31. Dot product
dot_product = np.dot(array1, array4)
print("Dot product of Array1 and Array4:", dot_product)

# 32. Matrix trace
matrix_trace = np.trace(matrix1)
print("Trace of Matrix1:", matrix_trace)

# 33. Create identity matrix
identity_matrix = np.eye(3)
print("Identity matrix:\n", identity_matrix)

# 34. Array reshaping
reshaped_array = np.reshape(array4, (5, 1))
print("Reshaped Array4:\n", reshaped_array)

# 35. Maximum value
max_value = np.max(array4)
print("Maximum value in Array4:", max_value)

# 36. Minimum value
min_value = np.min(array4)
print("Minimum value in Array4:", min_value)

# 37. Standard deviation
std_dev = np.std(array4)
print("Standard deviation of Array4:", std_dev)

# 38. Variance
variance = np.var(array4)
print("Variance of Array4:", variance)

# 39. Count non-zero elements
nonzero_count = np.count_nonzero(array4)
print("Count of non-zero elements in Array4:", nonzero_count)

# 40. Create zeros array
zeros_array = np.zeros((2, 3))
print("Zeros array:\n", zeros_array)

# 41. Create ones array
ones_array = np.ones((2, 3))
print("Ones array:\n", ones_array)

# 42. Full array
full_array = np.full((2, 3), 7)
print("Full array:\n", full_array)

# 43. Linspace
linspace_array = np.linspace(0, 10, 5)
print("Linspace array:", linspace_array)

# 44. Meshgrid
x, y = np.meshgrid(np.arange(3), np.arange(3))
print("Meshgrid x:\n", x)
print("Meshgrid y:\n", y)

# 45. Matrix rank
matrix_rank = np.linalg.matrix_rank(matrix1)
print("Matrix rank of Matrix1:", matrix_rank)

# 46. Histogram
hist, bins = np.histogram(array4, bins=5)
print("Histogram of Array4:", hist)
print("Bins:", bins)

# 47. Array sum along axis
sum_along_axis = np.sum(array2, axis=0)
print("Sum along axis 0 of Array2:", sum_along_axis)

# 48. Array mean along axis
mean_along_axis = np.mean(array2, axis=1)
print("Mean along axis 1 of Array2:", mean_along_axis)

# 49. Identity matrix check
is_identity = np.allclose(np.dot(identity_matrix, identity_matrix), identity_matrix)
print("Is identity matrix:", is_identity)

# 50. Element-wise comparison
comparison = array1 > 3
print("Element-wise comparison (Array1 > 3):", comparison)


Array1: [1 2 3 4 5]
Array2:
 [[1 2 3]
 [4 5 6]]
Array1 shape: (5,)
Array2 shape: (2, 3)
Array1 size: 5
Array2 size: 6
Array3 reshaped:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Slice1: [4 5 6 7]
Slice2: [ 2  6 10]
Array1 + Array4: [11 22 33 44 55]
Array1 * Array4: [ 10  40  90 160 250]
Array1 ** 2: [ 1  4  9 16 25]
Sine of Array1: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Log of Array4: [2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
Sum of Array1: 15
Mean of Array4: 30.0
Broadcasting:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]
Horizontally stacked array:
 [[ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]
 [ 5 50]]
Split array 1:
 [[1]
 [2]
 [3]
 [4]
 [5]]
Split array 2:
 [[10]
 [20]
 [30]
 [40]
 [50]]
Copied Array7: [1 2 3 4 5]
Matrix multiplication:
 [[19 22]
 [43 50]]
Matrix determinant: -2.0000000000000004
Random array:
 [[6.65310957e-04 5.98144758e-01 7.98218668e-01]
 [7.15726615e-01 6.39889270e-01 7.53644168e-01]
 [6.26536105e-01 5.47388558e-01 2.36006171e-01]]
Sorted Array